algoritmo "3"
// Função :
// Autor : Esther Oliveira costa
// Data : 19/10/2020
// Seção de Declarações 
var
vet : vetor[1..10] de inteiro
cont , par , impar : inteiro

inicio
par <-0
impar <-0

para cont de 1 ate 10 passo 1 faca
escreval (" informe um numero ")
leia (ve[cont])
se (vet[cont]mod 2= 0 ) entao
par <- par + 1

fimse
fimpara

escreval (" par :", par )
escreval (" impar :", impar )
fimalgoritmo
